package com.interviewos.ai.dto;

import com.interviewos.ai.model.DifficultyLevel;
import com.interviewos.ai.model.InterviewTrack;
import java.util.List;

/**
 * Structured interview question generated by the AI engine.
 */
public record GenerateQuestionResponse(
        String title,
        InterviewTrack track,
        DifficultyLevel difficulty,
        String problemStatement,
        String starterCode,
        List<String> hints,
        List<String> evaluationCriteria
) {}