package com.interviewos.ai.dto;

import com.interviewos.ai.model.DifficultyLevel;
import com.interviewos.ai.model.InterviewTrack;
import lombok.Builder;

import java.util.List;
import java.util.Map;

/**
 * Structured interview question generated by the AI engine / Question Bank.
 */
@Builder
public record GenerateQuestionResponse(
        String problemSlug,
        String title,
        InterviewTrack track,
        DifficultyLevel difficulty,
        String problemStatement,
        String starterCode,
        Map<String, String> starterCodeMap,
        Map<String, String> starterFiles,
        List<String> editablePaths,
        List<TestCaseView> sampleTests,
        List<String> hints,
        List<String> constraints,
        List<String> evaluationCriteria
) {
    // Backwards-compatible constructor for testing
    public GenerateQuestionResponse(
            String title,
            InterviewTrack track,
            DifficultyLevel difficulty,
            String problemStatement,
            String starterCode,
            List<String> hints,
            List<String> evaluationCriteria
    ) {
        this(
                title != null ? title.toLowerCase().replaceAll("[^a-z0-9]+", "-").replaceAll("(^-|-$)", "") : "custom-question",
                title,
                track,
                difficulty,
                problemStatement,
                starterCode,
                Map.of("java", starterCode != null ? starterCode : ""),
                Map.of(),
                List.of(),
                List.of(),
                hints,
                List.of(),
                evaluationCriteria
        );
    }

    public record TestCaseView(
            String name,
            String input,
            String expectedOutput
    ) {}
}