server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:evaluationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

services:
  session-service:
    url: ${SERVICES_SESSION_SERVICE_URL:http://interview-session-service:8081}
  proctor-service:
    url: ${SERVICES_PROCTOR_SERVICE_URL:http://proctor-sentinel-service:8083}