package com.interviewos.ai.client;

import com.interviewos.ai.model.ModelProvider;

/**
 * Universal interface for all AI model inference adapters.
 */
public interface AiClient {

    /**
     * Checks if this client handles the requested provider.
     */
    boolean supports(ModelProvider provider);

    /**
     * Executes prompt inference against the target AI provider.
     *
     * @param provider           The target provider (e.g. GROQ, GEMINI, QWEN)
     * @param systemInstruction System role and constraints
     * @param userPrompt         The prompt content
     * @param apiKey             Candidate's BYOK API key (optional for local Ollama)
     * @param customModel        Optional model override
     * @return Raw text/JSON generated by the LLM
     */
    String generateCompletion(
            ModelProvider provider,
            String systemInstruction,
            String userPrompt,
            String apiKey,
            String customModel
    );
}