package com.interviewos.ai.client;

import com.interviewos.ai.model.ModelProvider;

/**
 * Universal interface for all AI model inference adapters.
 */
public interface AiClient {

    /**
     * Checks if this client handles the requested provider.
     */
    boolean supports(ModelProvider provider);

    /**
     * Executes prompt inference against the target AI provider.
     *
     * @param provider           The target provider (e.g. GROQ, GEMINI, QWEN)
     * @param systemInstruction System role and constraints
     * @param userPrompt         The prompt content
     * @param apiKey             Candidate's BYOK API key (optional for local Ollama)
     * @param customModel        Optional model override
     * @return Raw text/JSON generated by the LLM
     */
    String generateCompletion(
            ModelProvider provider,
            String systemInstruction,
            String userPrompt,
            String apiKey,
            String customModel
    );

    /**
     * Executes multimodal vision prompt inference against the target AI provider.
     * Default implementation falls back to text-only completion.
     *
     * @param provider           The target provider (e.g. GEMINI, OPENAI)
     * @param systemInstruction System role and constraints
     * @param userPrompt         The prompt content
     * @param imageBytes         Binary PNG/JPEG image payload
     * @param mimeType           Image MIME type (e.g. "image/png")
     * @param apiKey             Candidate's BYOK API key
     * @param customModel        Optional model override
     * @return Raw text/JSON generated by the LLM
     */
    default String generateCompletionWithVision(
            ModelProvider provider,
            String systemInstruction,
            String userPrompt,
            byte[] imageBytes,
            String mimeType,
            String apiKey,
            String customModel
    ) {
        return generateCompletion(provider, systemInstruction, userPrompt, apiKey, customModel);
    }
}