apiVersion: 1

datasources:
  # 1. Prometheus Metrics Datasource
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  # 2. Grafana Loki Logs Datasource
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceId=([a-fA-F0-9]+)"
          name: TraceID
          url: "$${__value.raw}"

  # 3. Grafana Tempo Traces Datasource
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: 'Loki'
        spanStartTimeShift: '1s'
        spanEndTimeShift: '1s'
        filterByTrace: true
        filterBySpan: true
        tags: ['app', 'container']
